### ISSUE TITLE
New colors on docs.mulesoft.com

### ISSUE THREAD

**Issue by mmkociman** [mulesoft/docs-general#6]
The code sample colors in the new docs border on unreadable. An example is the lime-green on the gray color scheme which makes trying to read the sample code almost painful

**Comment by Mulesoft-Mysti** [comment]
We are working correcting this. Apologies for the color in the meantime. I'll post here when we have an ETA.

**Comment by Mulesoft-Mysti** [comment]
This issue is on the team backlog.
