### ISSUE TITLE
Incorrect info

### ISSUE THREAD

**Issue by sujatha-mule** [mulesoft/docs-general#73]
Hi,
In below URL, under "Support Matrix for Control Plane Hosting Options" section, the last row and last column value is "Y". i.e "Customer-hosted Runtimes" is supported for "Anypoint platform PCE".

This has contradiction with:
Same page, under "Control Plane and Runtime Plane Support Matrix" section, second row last column is mentioned as "N". i.e "Standalone runtimes" is not supported for "Anypoint platform PCE".

Please clarify why these two sections are not in sync.

URL:
https://docs.mulesoft.com/general/intro-platform-hosting#support-matrix-for-control-plane-hosting-options

Thank you
Sujatha

**Comment by valkyrie69** [comment]
Hello @sujatha-mule It looks like this issue was resolved, so I am closing this issue. Thank you for pointing out the contradiction.
